# Generated by IBM TransformationAdvisor
# Wed Oct 17 14:24:47 UTC 2018


#IMAGE: Get the base image for Liberty
FROM websphere-liberty:webProfile7

RUN ls /opt/ibm/wlp
RUN ls /etc/wlp
RUN ls .
RUN ls ./tmp
#BINARIES: Add in all necessary application binaries
COPY ./server.xml /config
#COPY ./binary/application/* /config/dropins/
COPY ./modresorts.war /config/dropins/

#FEATURES: Install any features that are required
RUN apt-get update && apt-get dist-upgrade -y \
#RUN ls /var/lib/apt/lists/
#RUN rm -rf /var/lib/apt/lists/*
RUN /opt/ibm/wlp/bin/installUtility install  --acceptLicense \
	jsp-2.3 \
	servlet-3.1; exit 0


# Upgrade to production license if URL to JAR provided
ARG LICENSE_JAR_URL
RUN \
   if [ $LICENSE_JAR_URL ]; then \
     wget $LICENSE_JAR_URL -O /tmp/license.jar \
     && java -jar /tmp/license.jar -acceptLicense /opt/ibm \
     && rm /tmp/license.jar; \
   fi
