# Generated by IBM TransformationAdvisor
# Wed Oct 17 14:24:47 UTC 2018


#IMAGE: Get the base image for Liberty
FROM websphere-liberty:webProfile7


COPY ./server.xml /config

#BINARIES: Add in all necessary application binaries
#COPY ./binary/application/* /config/dropins/
COPY ./binary-modresorts-1.0.war /config/dropins/modresorts-1.0.war
RUN ls -la /config/dropins/

#TODO: download DB2 driver $LIBERTY_HOME/wlp/usr/shared/resources/db2
RUN mkdir /opt/ibm/wlp/usr/shared/resources/db2
COPY ./db2driver-db2jcc.jar /opt/ibm/wlp/usr/shared/resources/db2/db2jcc.jar
RUN ls -la /opt/ibm/wlp/usr/shared/resources/db2/

#TODO: download MQ driver

#FEATURES: Install any features that are required
RUN apt-get update && apt-get dist-upgrade -y \
#RUN ls /var/lib/apt/lists/
#RUN rm -rf /var/lib/apt/lists/*
RUN /opt/ibm/wlp/bin/installUtility install  --acceptLicense \
	jsp-2.3 \
	servlet-3.1; exit 0


# Upgrade to production license if URL to JAR provided
ARG LICENSE_JAR_URL
RUN \
   if [ $LICENSE_JAR_URL ]; then \
     wget $LICENSE_JAR_URL -O /tmp/license.jar \
     && java -jar /tmp/license.jar -acceptLicense /opt/ibm \
     && rm /tmp/license.jar; \
   fi
