#!groovy

// Generated by IBM TransformationAdvisor
// Wed Jan 30 14:05:28 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'senderwar'
    mvnCommands = '-X initialize process-resources verify'
    test='false'
}