#!groovy

// Generated by IBM TransformationAdvisor
// Thu Oct 04 18:46:38 UTC 2018

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}