#!groovy

// Generated by IBM TransformationAdvisor
// Wed Oct 17 14:24:47 UTC 2018

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}